#!/usr/bin/perl -w
#
# $Id: uagent,v 1.2 2004/02/22 06:04:31 jim Exp jim $
#
# Todo:
# -----
# 1) Hey, I want to be able to filter stuff out. You know, like when
# people add comments to someone's blog. I don't want to know about that.
#
# 2) Hey, if two people are looking at the same blog, you should probably
# aggregate.
#



use LWP::Simple;
use strict;

my $url     = "";  
my $sec     = "";       # sleep for this many seconds
my $doc     = get $url;
my $md5a    = "";
my $md5b    = "";

if ($#ARGV == 1) {
	chomp($url = $ARGV[0]);
	chomp($sec = $ARGV[1]);
} else {
	die "usage: uagent url seconds\n";
}
my $i_sentinel = 1;

$md5a = get_md5($url);
my $s_furl = furl($url);
my $outfile = $s_furl . "_out1.txt";
my $oldpage = $s_furl . "_old_page.txt";
`cp $outfile $oldpage`;
print $md5a . "\n";

while($i_sentinel > 0)
{
	sleep $sec;
	$md5b = get_md5($url);
	print $md5b . "\n";
	unless ($md5b eq $md5a) {
		$i_sentinel = 0;
		# mail barce@well.com here
		`echo "$url has changed" | mail barce\@well.com -s uagent`;
	}
}

sub furl {
	my $url    = shift;
	my $s_furl = $url;
	$s_furl =~ s/\//_/g;
	return $s_furl;
}

sub get_md5 {

	my $url  = shift;
	my $s_furl = furl($url);
	my $file = $s_furl . "_out1.txt";
	my $md5  = "";
	$doc = get $url;
	open(OUT, ">$file") || die "Cannot open $file: $!";
	print OUT $doc;
	close(OUT) || die "Cannot close $file: $!";
	$md5 = `md5 $file`;
	chomp($md5);
	return $md5;
}

